import React, { useState, useEffect } from 'react';
import Papa from 'papaparse';
import { supabase } from './supabase';
import * as yaml from 'js-yaml';

interface Game {
  id: string;
  kickoff_et: string;
  away: string;
  home: string;
  spread_away: number;
  spread_home: number;
  total: number;
  spreads_book: string;
}

interface TeamPick {
  gameId: string;
  team: string; // team name selected
  spread: number; // spread for the selected team
  correct?: boolean; // whether this pick was correct (optional, for future use)
}

interface Pick {
  userId: string;
  week: number;
  picks: TeamPick[];
  correct: number;
}

interface User {
  id: string;
  name: string;
  total: number;
  percentage: number;
}

function App() {
  const [games, setGames] = useState<Game[]>([]);
  const [users] = useState<User[]>([
    { id: 'jacob', name: 'Jacob', total: 0, percentage: 0 },
    { id: 'cam', name: 'Cam', total: 0, percentage: 0 },
    { id: 'con', name: 'Con', total: 0, percentage: 0 },
    { id: 'nathan', name: 'Nathan', total: 0, percentage: 0 },
    { id: 'shane', name: 'Shane', total: 0, percentage: 0 },
    { id: 'max', name: 'Max', total: 0, percentage: 0 },
  ]);
  const [picks, setPicks] = useState<Pick[]>([]);
  const [currentWeek, setCurrentWeek] = useState(1);
  const [selectedUser, setSelectedUser] = useState<string>('jacob');
  const [activeTab, setActiveTab] = useState<'picks' | 'leaderboard' | 'chart' | 'history'>('picks');
  const [teamAbbreviations, setTeamAbbreviations] = useState<{[key: string]: string}>({});

  useEffect(() => {
    // Load games from CSV (we'll create this from your odds script)
    loadGames();
    loadPicks();
    loadTeamAbbreviations();
  }, []);

  const loadGames = async () => {
    try {
      // Load games from CSV file generated by the odds script
      const response = await fetch(`${process.env.PUBLIC_URL}/nfl_lines_week.csv`);
      const csvText = await response.text();
      
      Papa.parse(csvText, {
        header: true,
        complete: (results) => {
          const csvGames: Game[] = results.data.map((row: any, index: number) => ({
            id: `${index + 1}`,
            kickoff_et: row.kickoff_et,
            away: row.away,
            home: row.home,
            spread_away: parseFloat(row.spread_away),
            spread_home: parseFloat(row.spread_home),
            total: parseFloat(row.total),
            spreads_book: row.spreads_book
          })).filter(game => game.away && game.home); // Filter out empty rows
          
          setGames(csvGames);
        },
        error: (error: any) => {
          console.error('Error parsing CSV:', error);
          // Fallback to sample data if CSV fails to load
          loadSampleGames();
        }
      });
    } catch (error) {
      console.error('Error loading CSV file:', error);
      // Fallback to sample data if CSV fails to load
      loadSampleGames();
    }
  };

  const loadSampleGames = () => {
    // Fallback if CSV fails to load - should not happen in production
    console.error('Failed to load games from CSV');
    setGames([]);
  };

  const loadTeamAbbreviations = async () => {
    try {
      const response = await fetch(`${process.env.PUBLIC_URL}/teamAbbreviations.yaml`);
      if (!response.ok) {
        console.error('Failed to load team abbreviations');
        return;
      }
      const yamlText = await response.text();
      const data = yaml.load(yamlText) as { teams: {[key: string]: string} };
      setTeamAbbreviations(data.teams);
    } catch (error) {
      console.error('Error loading team abbreviations:', error);
    }
  };

  const loadPicks = async () => {
    try {
      const { data, error } = await supabase
        .from('picks')
        .select('*')
        .order('week', { ascending: true });

      if (error) throw error;

      // Group picks by user and week
      const groupedPicks = data.reduce((acc: any, pick: any) => {
        const key = `${pick.user_id}-${pick.week}`;
        if (!acc[key]) {
          acc[key] = {
            userId: pick.user_id,
            week: pick.week,
            picks: [],
            correct: 0
          };
        }
        
        acc[key].picks.push({
          gameId: pick.game_id,
          team: pick.team,
          spread: pick.spread,
          correct: pick.correct
        });
        
        if (pick.correct === true) {
          acc[key].correct++;
        }
        
        return acc;
      }, {});

      const picksArray = Object.values(groupedPicks);
      setPicks(picksArray as Pick[]);
      
    } catch (error) {
      console.error('Error loading picks:', error);
      setPicks([]);
    }
  };

  const savePicks = async (userId: string, week: number, selectedPicks: TeamPick[]) => {
    try {
      // First, delete any existing picks for this user/week
      await supabase
        .from('picks')
        .delete()
        .eq('user_id', userId)
        .eq('week', week);

      // Then insert the new picks
      const pickRecords = selectedPicks.map(pick => ({
        user_id: userId,
        week: week,
        game_id: pick.gameId,
        team: pick.team,
        spread: pick.spread,
        correct: null // Will be set later when games finish
      }));

      const { error } = await supabase
        .from('picks')
        .insert(pickRecords);

      if (error) throw error;

      // Reload picks to update UI
      await loadPicks();
      
      alert('Picks saved successfully!');
      
    } catch (error) {
      console.error('Error saving picks:', error);
      alert('Error saving picks. Please try again.');
    }
  };

  const getCurrentUserPicks = () => {
    return picks.find(p => p.userId === selectedUser && p.week === currentWeek);
  };


  return (
    <div className="min-h-screen bg-gray-50">
      <div className="max-w-7xl mx-auto py-6 px-4 sm:px-6 lg:px-8">
        <div className="text-center mb-8">
          <h1 className="text-4xl font-bold text-gray-900 mb-2">
            2025-26 NFL Spread Pick-Em
          </h1>
          <p className="text-lg text-gray-600">
            Pick 3 teams against the spread each week
          </p>
        </div>

        {/* Tab Navigation */}
        <div className="mb-8">
          <nav className="flex space-x-8">
            {[
              { key: 'picks', label: 'Make Picks' },
              { key: 'leaderboard', label: 'Leaderboard' },
              { key: 'chart', label: 'Pick Chart' },
              { key: 'history', label: 'Pick History' }
            ].map(tab => (
              <button
                key={tab.key}
                onClick={() => setActiveTab(tab.key as any)}
                className={`py-2 px-1 border-b-2 font-medium text-sm ${
                  activeTab === tab.key
                    ? 'border-blue-500 text-blue-600'
                    : 'border-transparent text-gray-500 hover:text-gray-700 hover:border-gray-300'
                }`}
              >
                {tab.label}
              </button>
            ))}
          </nav>
        </div>

        {/* Controls - only show on picks and history tabs */}
        {(activeTab === 'picks' || activeTab === 'history') && (
          <>
            {/* User Selection */}
            <div className="mb-8">
              <label className="block text-sm font-medium text-gray-700 mb-2">
                Select User
              </label>
              <select
                value={selectedUser}
                onChange={(e) => setSelectedUser(e.target.value)}
                className="block w-full max-w-xs rounded-md border-gray-300 shadow-sm focus:border-blue-500 focus:ring-blue-500"
              >
                {users.map(user => (
                  <option key={user.id} value={user.id}>
                    {user.name}
                  </option>
                ))}
              </select>
            </div>
          </>
        )}

        {/* Tab Content */}
        {activeTab === 'picks' && (
          <div className="mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-6">
              {users.find(u => u.id === selectedUser)?.name}'s Picks - Week {currentWeek}
            </h2>
            
            <PickInterface
              games={games}
              currentPicks={getCurrentUserPicks()?.picks || []}
              onSavePicks={(picks) => savePicks(selectedUser, currentWeek, picks)}
            />
          </div>
        )}

        {activeTab === 'leaderboard' && (
          <div className="bg-white rounded-lg shadow p-6 mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Leaderboard
            </h2>
            <Leaderboard users={users} picks={picks} />
          </div>
        )}

        {activeTab === 'chart' && (
          <div className="bg-white rounded-lg shadow p-6 mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">Pick Chart - All Users</h2>
            <PickChart picks={picks} users={users} selectedUser={selectedUser} currentWeek={currentWeek} games={games} teamAbbreviations={teamAbbreviations} />
          </div>
        )}

        {activeTab === 'history' && (
          <div className="bg-white rounded-lg shadow p-6 mb-8">
            <h2 className="text-2xl font-semibold text-gray-900 mb-4">
              Pick History - {users.find(u => u.id === selectedUser)?.name}
            </h2>
            <PickHistory picks={picks} selectedUser={selectedUser} currentWeek={currentWeek} games={games} />
          </div>
        )}
      </div>
    </div>
  );
}

interface PickInterfaceProps {
  games: Game[];
  currentPicks: TeamPick[];
  onSavePicks: (picks: TeamPick[]) => void;
}

function PickInterface({ games, currentPicks, onSavePicks }: PickInterfaceProps) {
  const [selectedPicks, setSelectedPicks] = useState<TeamPick[]>(currentPicks);
  const [hasExistingPicks, setHasExistingPicks] = useState<boolean>(currentPicks.length > 0);
  
  // Update selectedPicks when currentPicks changes (e.g., when user changes)
  React.useEffect(() => {
    setSelectedPicks(currentPicks);
    setHasExistingPicks(currentPicks.length > 0);
  }, [currentPicks]);

  const handleTeamToggle = (gameId: string, team: string, spread: number) => {
    // Don't allow changes if the game is locked
    const game = games.find(g => g.id === gameId);
    if (game && isGameLocked(game)) {
      return;
    }

    setSelectedPicks(prev => {
      // Check if this team is already selected
      const existingPickIndex = prev.findIndex(p => p.gameId === gameId && p.team === team);
      
      if (existingPickIndex >= 0) {
        // Remove the selected team
        return prev.filter((_, index) => index !== existingPickIndex);
      }
      
      // Check if the other team from this game is already selected
      const otherTeamIndex = prev.findIndex(p => p.gameId === gameId && p.team !== team);
      
      if (otherTeamIndex >= 0) {
        // Replace the other team selection with this team
        const newPicks = [...prev];
        newPicks[otherTeamIndex] = { gameId, team, spread };
        return newPicks;
      }
      
      // Add new team selection if less than 3 picks
      if (prev.length < 3) {
        return [...prev, { gameId, team, spread }];
      }
      
      // Can't add more than 3 picks
      return prev;
    });
  };

  const handleSave = () => {
    if (selectedPicks.length === 3) {
      onSavePicks(selectedPicks);
    }
  };

  // Check if current picks are different from original picks
  const arePicksModified = () => {
    if (!hasExistingPicks && selectedPicks.length > 0) return true;
    if (hasExistingPicks && selectedPicks.length !== currentPicks.length) return true;
    
    // Check if any picks have changed
    return selectedPicks.some(pick => {
      const originalPick = currentPicks.find(op => op.gameId === pick.gameId);
      return !originalPick || originalPick.team !== pick.team || originalPick.spread !== pick.spread;
    });
  };

  const getButtonText = () => {
    if (!hasExistingPicks) {
      return `Save Picks (${selectedPicks.length}/3)`;
    } else if (arePicksModified()) {
      return `Update Picks (${selectedPicks.length}/3)`;
    } else {
      return `Picks Saved (${selectedPicks.length}/3)`;
    }
  };

  const formatGameTime = (kickoffEt: string) => {
    const date = new Date(kickoffEt);
    
    // Get user's timezone for display
    const userTimezone = Intl.DateTimeFormat().resolvedOptions().timeZone;
    const timezoneAbbr = new Date().toLocaleTimeString('en-US', { 
      timeZoneName: 'short' 
    }).split(' ')[2];
    
    return date.toLocaleDateString('en-US', { 
      weekday: 'short',
      month: 'short', 
      day: 'numeric',
      hour: 'numeric',
      minute: '2-digit',
      timeZone: userTimezone
    }) + ` ${timezoneAbbr}`;
  };


  const getGameSelectionState = (gameId: string) => {
    const gamePick = selectedPicks.find(p => p.gameId === gameId);
    return gamePick ? gamePick.team : null;
  };

  const isGameLocked = (game: Game) => {
    const gameTime = new Date(game.kickoff_et);
    const now = new Date();
    return now >= gameTime;
  };

  const getTeamLogo = (teamName: string) => {
    // Simple mapping of team names to logo URLs (using ESPN's logos)
    const teamLogos: { [key: string]: string } = {
      'Dallas Cowboys': 'https://a.espncdn.com/i/teamlogos/nfl/500/dal.png',
      'Philadelphia Eagles': 'https://a.espncdn.com/i/teamlogos/nfl/500/phi.png',
      'Kansas City Chiefs': 'https://a.espncdn.com/i/teamlogos/nfl/500/kc.png',
      'Los Angeles Chargers': 'https://a.espncdn.com/i/teamlogos/nfl/500/lac.png',
      'Arizona Cardinals': 'https://a.espncdn.com/i/teamlogos/nfl/500/ari.png',
      'New Orleans Saints': 'https://a.espncdn.com/i/teamlogos/nfl/500/no.png',
      'Tampa Bay Buccaneers': 'https://a.espncdn.com/i/teamlogos/nfl/500/tb.png',
      'Atlanta Falcons': 'https://a.espncdn.com/i/teamlogos/nfl/500/atl.png',
      'Carolina Panthers': 'https://a.espncdn.com/i/teamlogos/nfl/500/car.png',
      'Jacksonville Jaguars': 'https://a.espncdn.com/i/teamlogos/nfl/500/jax.png',
      'Cincinnati Bengals': 'https://a.espncdn.com/i/teamlogos/nfl/500/cin.png',
      'Cleveland Browns': 'https://a.espncdn.com/i/teamlogos/nfl/500/cle.png',
      'Miami Dolphins': 'https://a.espncdn.com/i/teamlogos/nfl/500/mia.png',
      'Indianapolis Colts': 'https://a.espncdn.com/i/teamlogos/nfl/500/ind.png',
      'Las Vegas Raiders': 'https://a.espncdn.com/i/teamlogos/nfl/500/lv.png',
      'New England Patriots': 'https://a.espncdn.com/i/teamlogos/nfl/500/ne.png',
      'New York Giants': 'https://a.espncdn.com/i/teamlogos/nfl/500/nyg.png',
      'Washington Commanders': 'https://a.espncdn.com/i/teamlogos/nfl/500/wsh.png',
      'Pittsburgh Steelers': 'https://a.espncdn.com/i/teamlogos/nfl/500/pit.png',
      'New York Jets': 'https://a.espncdn.com/i/teamlogos/nfl/500/nyj.png',
      'Tennessee Titans': 'https://a.espncdn.com/i/teamlogos/nfl/500/ten.png',
      'Denver Broncos': 'https://a.espncdn.com/i/teamlogos/nfl/500/den.png',
      'San Francisco 49ers': 'https://a.espncdn.com/i/teamlogos/nfl/500/sf.png',
      'Seattle Seahawks': 'https://a.espncdn.com/i/teamlogos/nfl/500/sea.png',
      'Detroit Lions': 'https://a.espncdn.com/i/teamlogos/nfl/500/det.png',
      'Green Bay Packers': 'https://a.espncdn.com/i/teamlogos/nfl/500/gb.png',
      'Houston Texans': 'https://a.espncdn.com/i/teamlogos/nfl/500/hou.png',
      'Los Angeles Rams': 'https://a.espncdn.com/i/teamlogos/nfl/500/lar.png',
      'Baltimore Ravens': 'https://a.espncdn.com/i/teamlogos/nfl/500/bal.png',
      'Buffalo Bills': 'https://a.espncdn.com/i/teamlogos/nfl/500/buf.png',
      'Minnesota Vikings': 'https://a.espncdn.com/i/teamlogos/nfl/500/min.png',
      'Chicago Bears': 'https://a.espncdn.com/i/teamlogos/nfl/500/chi.png'
    };
    return teamLogos[teamName] || '';
  };

  return (
    <div>
      <div className="mb-4">
        <p className="text-sm text-gray-600">
          {hasExistingPicks 
            ? `Update your picks - Select exactly 3 teams (${selectedPicks.length}/3 selected)`
            : `Select exactly 3 teams (${selectedPicks.length}/3 selected)`
          }
        </p>
        {hasExistingPicks && !arePicksModified() && selectedPicks.length === 3 && (
          <p className="text-sm text-green-600 mt-1">
            ✓ Your picks have been saved. Make changes to update them.
          </p>
        )}
      </div>
      
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4 mb-6">
        {games.map(game => {
          const selectedTeam = getGameSelectionState(game.id);
          const canSelect = selectedPicks.length < 3 || selectedTeam !== null;
          const gameLocked = isGameLocked(game);
          
          return (
            <div key={game.id} className={`border rounded-lg p-4 shadow-md transition-shadow ${
              gameLocked ? 'bg-gray-50 border-gray-300' : 'bg-white hover:shadow-lg'
            }`}>
              <div className="mb-4">
                <div className="flex items-center justify-between">
                  <div>
                    <span className={`text-lg font-bold ${gameLocked ? 'text-gray-500' : 'text-gray-900'}`}>
                      {game.away} @ {game.home}
                    </span>
                    <span className={`text-sm ml-3 ${gameLocked ? 'text-gray-400' : 'text-gray-500'}`}>
                      {formatGameTime(game.kickoff_et)}
                    </span>
                  </div>
                  {gameLocked && (
                    <div className="flex items-center text-red-600">
                      <svg className="w-5 h-5 mr-1" fill="currentColor" viewBox="0 0 20 20">
                        <path fillRule="evenodd" d="M5 9V7a5 5 0 0110 0v2a2 2 0 012 2v5a2 2 0 01-2 2H5a2 2 0 01-2-2v-5a2 2 0 012-2zm8-2v2H7V7a3 3 0 016 0z" clipRule="evenodd" />
                      </svg>
                      <span className="text-xs font-medium">LOCKED</span>
                    </div>
                  )}
                </div>
              </div>
              
              <div className="space-y-3">
                {/* Away Team Option */}
                <div 
                  className={`flex items-center space-x-3 p-3 rounded border transition-colors ${
                    gameLocked
                      ? 'border-gray-300 bg-gray-100 cursor-not-allowed opacity-60'
                      : selectedTeam === game.away
                        ? 'border-blue-500 bg-blue-50 cursor-pointer' 
                        : canSelect
                          ? 'border-gray-200 hover:border-gray-300 hover:bg-gray-50 cursor-pointer'
                          : 'border-gray-200 bg-gray-100 cursor-not-allowed opacity-50'
                  }`}
                  onClick={() => !gameLocked && canSelect && handleTeamToggle(game.id, game.away, game.spread_away)}
                >
                  <input
                    type="radio"
                    name={`game-${game.id}`}
                    checked={selectedTeam === game.away}
                    onChange={() => !gameLocked && canSelect && handleTeamToggle(game.id, game.away, game.spread_away)}
                    disabled={!canSelect || gameLocked}
                    className="h-4 w-4 text-blue-600 focus:ring-blue-500"
                  />
                  {getTeamLogo(game.away) && (
                    <img 
                      src={getTeamLogo(game.away)} 
                      alt={game.away}
                      className="w-8 h-8 object-contain"
                      onError={(e) => { e.currentTarget.style.display = 'none'; }}
                    />
                  )}
                  <div className="flex-1">
                    <div className={`font-medium text-lg ${
                      gameLocked ? 'text-gray-500' : 'text-gray-900'
                    }`}>
                      {game.away}
                    </div>
                    <div className={`text-lg font-bold ${
                      gameLocked ? 'text-gray-400' : 'text-blue-600'
                    }`}>
                      {game.spread_away > 0 ? `+${game.spread_away}` : game.spread_away}
                    </div>
                  </div>
                </div>

                {/* Home Team Option */}
                <div 
                  className={`flex items-center space-x-3 p-3 rounded border transition-colors ${
                    gameLocked
                      ? 'border-gray-300 bg-gray-100 cursor-not-allowed opacity-60'
                      : selectedTeam === game.home
                        ? 'border-blue-500 bg-blue-50 cursor-pointer' 
                        : canSelect
                          ? 'border-gray-200 hover:border-gray-300 hover:bg-gray-50 cursor-pointer'
                          : 'border-gray-200 bg-gray-100 cursor-not-allowed opacity-50'
                  }`}
                  onClick={() => !gameLocked && canSelect && handleTeamToggle(game.id, game.home, game.spread_home)}
                >
                  <input
                    type="radio"
                    name={`game-${game.id}`}
                    checked={selectedTeam === game.home}
                    onChange={() => !gameLocked && canSelect && handleTeamToggle(game.id, game.home, game.spread_home)}
                    disabled={!canSelect || gameLocked}
                    className="h-4 w-4 text-blue-600 focus:ring-blue-500"
                  />
                  {getTeamLogo(game.home) && (
                    <img 
                      src={getTeamLogo(game.home)} 
                      alt={game.home}
                      className="w-8 h-8 object-contain"
                      onError={(e) => { e.currentTarget.style.display = 'none'; }}
                    />
                  )}
                  <div className="flex-1">
                    <div className={`font-medium text-lg ${
                      gameLocked ? 'text-gray-500' : 'text-gray-900'
                    }`}>
                      {game.home}
                    </div>
                    <div className={`text-lg font-bold ${
                      gameLocked ? 'text-gray-400' : 'text-blue-600'
                    }`}>
                      {game.spread_home > 0 ? `+${game.spread_home}` : game.spread_home}
                    </div>
                  </div>
                </div>
              </div>
            </div>
          );
        })}
      </div>

      <button
        onClick={handleSave}
        disabled={selectedPicks.length !== 3 || (hasExistingPicks && !arePicksModified())}
        className={`w-full py-2 px-4 rounded-md ${
          selectedPicks.length !== 3 
            ? 'bg-gray-400 text-white cursor-not-allowed'
            : hasExistingPicks && !arePicksModified()
              ? 'bg-green-600 text-white cursor-not-allowed'
              : hasExistingPicks && arePicksModified()
                ? 'bg-orange-600 text-white hover:bg-orange-700'
                : 'bg-blue-600 text-white hover:bg-blue-700'
        }`}
      >
        {getButtonText()}
      </button>
    </div>
  );
}

interface LeaderboardProps {
  users: User[];
  picks: Pick[];
}

interface PickChartProps {
  picks: Pick[];
  users: User[];
  selectedUser: string;
  currentWeek: number;
  games: Game[];
  teamAbbreviations: {[key: string]: string};
}

interface PickHistoryProps {
  picks: Pick[];
  selectedUser: string;
  currentWeek: number;
  games: Game[];
}

function Leaderboard({ users, picks }: LeaderboardProps) {
  return (
    <div className="overflow-x-auto">
      <table className="min-w-full divide-y divide-gray-200">
        <thead className="bg-gray-50">
          <tr>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Name
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              Total
            </th>
            <th className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
              %
            </th>
          </tr>
        </thead>
        <tbody className="bg-white divide-y divide-gray-200">
          {users.map((user) => (
            <tr key={user.id}>
              <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900">
                {user.name}
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {user.total}
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                {user.percentage}%
              </td>
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

function PickChart({ picks, users, selectedUser, currentWeek, games, teamAbbreviations }: PickChartProps) {
  const weeks = Array.from({ length: 18 }, (_, i) => i + 1);
  
  const getPickInfo = (pick: TeamPick) => {
    // Use team abbreviation from YAML mapping
    const teamAbbr = teamAbbreviations[pick.team] || pick.team.split(' ').slice(-1)[0].substring(0, 3).toUpperCase();
    return `${teamAbbr} ${pick.spread > 0 ? '+' : ''}${pick.spread}`;
  };

  const getUserTotalCorrect = (userId: string) => {
    return picks.filter(p => p.userId === userId).reduce((sum, pick) => sum + pick.correct, 0);
  };

  const getUserTotalPicks = (userId: string) => {
    return picks.filter(p => p.userId === userId).length * 3;
  };

  const getUserPercentage = (userId: string) => {
    const total = getUserTotalPicks(userId);
    if (total === 0) return 0;
    return Math.round((getUserTotalCorrect(userId) / total) * 100);
  };

  return (
    <div className="overflow-x-auto">
      <table className="min-w-full divide-y divide-gray-200 text-xs">
        <thead className="bg-gray-50">
          <tr>
            <th className="px-2 py-2 text-left text-xs font-medium text-gray-500 uppercase">User</th>
            <th className="px-2 py-2 text-center text-xs font-medium text-gray-500 uppercase">Total</th>
            <th className="px-2 py-2 text-center text-xs font-medium text-gray-500 uppercase">%</th>
            {weeks.map(week => (
              <th key={week} className="px-1 py-2 text-center text-xs font-medium text-gray-500 uppercase">
                W{week}
              </th>
            ))}
          </tr>
        </thead>
        <tbody className="bg-white divide-y divide-gray-200">
          {users.map(user => {
            const userPicks = picks.filter(p => p.userId === user.id);
            const totalCorrect = getUserTotalCorrect(user.id);
            const percentage = getUserPercentage(user.id);
            
            return (
              <tr key={user.id} className="hover:bg-gray-50">
                <td className="px-2 py-2 whitespace-nowrap text-sm font-medium text-gray-900">
                  {user.name}
                </td>
                <td className="px-2 py-2 whitespace-nowrap text-sm text-center font-semibold text-gray-900">
                  {totalCorrect}
                </td>
                <td className="px-2 py-2 whitespace-nowrap text-sm text-center font-semibold text-gray-900">
                  {percentage}%
                </td>
                {weeks.map(week => {
                  const weekPick = userPicks.find(p => p.week === week);
                  const isCurrentWeek = week === currentWeek;
                  
                  return (
                    <td key={week} className={`px-1 py-2 text-center text-xs ${isCurrentWeek ? 'bg-blue-50' : ''}`}>
                      {weekPick ? (
                        <div className="text-left">
                          {weekPick.picks.map((pick, idx) => {
                            const isPending = pick.correct === null || pick.correct === undefined;
                            const textColorClass = isPending 
                              ? 'text-gray-400' 
                              : pick.correct 
                                ? 'text-green-600 font-medium' 
                                : 'text-red-500';
                            const resultIcon = isPending ? '⏳' : pick.correct ? '✅' : '❌';
                            
                            return (
                              <div key={idx} className="border-b border-gray-100 py-1 last:border-b-0">
                                <div className="flex items-center justify-between">
                                  <span className={`text-xs ${textColorClass}`}>
                                    {getPickInfo(pick)}
                                  </span>
                                  <span className="ml-1">
                                    {resultIcon}
                                  </span>
                                </div>
                              </div>
                            );
                          })}
                          <div className="font-semibold text-gray-700 text-xs mt-1 pt-1 border-t border-gray-200">
                            {weekPick.correct}/3
                          </div>
                        </div>
                      ) : (
                        <span className="text-gray-400">-</span>
                      )}
                    </td>
                  );
                })}
              </tr>
            );
          })}
        </tbody>
      </table>
    </div>
  );
}

function PickHistory({ picks, selectedUser, currentWeek, games }: PickHistoryProps) {
  const weeks = Array.from({ length: 18 }, (_, i) => i + 1);
  const userPicks = picks.filter(pick => pick.userId === selectedUser);
  
  const getPickInfo = (pick: TeamPick) => {
    // Extract just the mascot name for history view
    const mascotName = pick.team.split(' ').slice(-1)[0]; // Gets "Cowboys" from "Dallas Cowboys"
    const game = games.find(g => g.id === pick.gameId);
    if (!game) return `${mascotName} (${pick.spread > 0 ? '+' : ''}${pick.spread})`;
    
    const opponent = pick.team === game.away ? game.home : game.away;
    const opponentMascot = opponent.split(' ').slice(-1)[0]; // Gets mascot from opponent too
    const location = pick.team === game.away ? '@' : 'vs';
    return `${mascotName} ${location} ${opponentMascot} (${pick.spread > 0 ? '+' : ''}${pick.spread})`;
  };
  
  return (
    <div className="overflow-x-auto">
      <table className="min-w-full divide-y divide-gray-200">
        <thead className="bg-gray-50">
          <tr>
            <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Week</th>
            <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Pick 1</th>
            <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Pick 2</th>
            <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Pick 3</th>
            <th className="px-4 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">Correct</th>
          </tr>
        </thead>
        <tbody className="bg-white divide-y divide-gray-200">
          {weeks.map((week) => {
            const weekPick = userPicks.find(p => p.week === week);
            const isCurrentWeek = week === currentWeek;
            
            return (
              <tr key={week} className={isCurrentWeek ? 'bg-blue-50' : ''}>
                <td className={`px-4 py-3 whitespace-nowrap text-sm font-medium ${isCurrentWeek ? 'text-blue-900' : 'text-gray-900'}`}>
                  Week {week}
                </td>
                <td className={`px-4 py-3 whitespace-nowrap text-sm ${
                  weekPick?.picks[0] 
                    ? weekPick.picks[0].correct === null || weekPick.picks[0].correct === undefined
                      ? 'text-gray-400'
                      : weekPick.picks[0].correct 
                        ? 'text-green-600 font-medium' 
                        : 'text-red-500' 
                    : 'text-gray-500'
                }`}>
                  {weekPick?.picks[0] ? getPickInfo(weekPick.picks[0]) : '-'}
                </td>
                <td className={`px-4 py-3 whitespace-nowrap text-sm ${
                  weekPick?.picks[1] 
                    ? weekPick.picks[1].correct === null || weekPick.picks[1].correct === undefined
                      ? 'text-gray-400'
                      : weekPick.picks[1].correct 
                        ? 'text-green-600 font-medium' 
                        : 'text-red-500' 
                    : 'text-gray-500'
                }`}>
                  {weekPick?.picks[1] ? getPickInfo(weekPick.picks[1]) : '-'}
                </td>
                <td className={`px-4 py-3 whitespace-nowrap text-sm ${
                  weekPick?.picks[2] 
                    ? weekPick.picks[2].correct === null || weekPick.picks[2].correct === undefined
                      ? 'text-gray-400'
                      : weekPick.picks[2].correct 
                        ? 'text-green-600 font-medium' 
                        : 'text-red-500' 
                    : 'text-gray-500'
                }`}>
                  {weekPick?.picks[2] ? getPickInfo(weekPick.picks[2]) : '-'}
                </td>
                <td className="px-4 py-3 whitespace-nowrap text-sm text-gray-500">
                  {weekPick ? `${weekPick.correct}/3` : '-'}
                </td>
              </tr>
            );
          })}
        </tbody>
      </table>
      
      {userPicks.length === 0 && (
        <div className="text-center py-8 text-gray-500">
          No picks found for this user.
        </div>
      )}
    </div>
  );
}

export default App;
